<<<<<<< HEAD

SET NOCOUNT ON
GO

USE master
GO
if exists (select * from sysdatabases where name='HocVien')
		drop database HocVien
go
create database HocVien
go

Use HocVien
Go

CREATE TABLE TTHocVien(
MaHV char(10) Primary Key,
TenHV nvarchar(25),
Gioitinh bit,
Ngaysinh datetime,
Quenquan nvarchar(100)
)
Go
Create Table LopHoc(
MaLop char(7) Primary Key,
TenLop nvarchar(100)
)
Go
Create Table HocKy(
	MaHK char(2) Primary Key,
	TenHK nvarchar(50)
)
GO
Create Table MonHoc(
	MaMon char(5) Primary Key,
	TenMon nvarchar(100),
	MaHK char(2) Foreign Key References HocKy(MaHK)
)
Go

Create Table TTDiemThi(
	MaHV char(10) Foreign Key References TTHocVien(MaHV),
	MaLop char(7) Foreign Key References LopHoc(MaLop),
	MaMon char(5) Foreign Key References MonHoc(MaMon),
	Diem float,
	Constraint MaDiemThi Primary Key (MaHV,MaLop,MaMon),

)


=======
USE [master]
GO

/****** Object:  Database [HocVien]    Script Date: 1/3/2023 11:13:37 AM ******/
CREATE DATABASE [HocVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HocVien', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\HocVien.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HocVien_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\HocVien_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HocVien] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HocVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HocVien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HocVien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HocVien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HocVien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HocVien] SET ARITHABORT OFF 
GO

ALTER DATABASE [HocVien] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HocVien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HocVien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HocVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HocVien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HocVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HocVien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HocVien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HocVien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HocVien] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HocVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HocVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HocVien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HocVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HocVien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HocVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HocVien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HocVien] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HocVien] SET  MULTI_USER 
GO

ALTER DATABASE [HocVien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HocVien] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HocVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HocVien] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HocVien] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HocVien] SET  READ_WRITE 
GO
>>>>>>> ce1b5dfb0165cfadcb49aecfc34b91f10f42a4e4

